### ISSUE TITLE
"sudo apt install fonts-powerline" has no installation candidate in latest kali-linux  2024.3 

### ISSUE THREAD

**Issue by MainakMa** [techchipnet/p10k#1]
all steps worked sequentially after the line " sudo apt install fonts-powerline"  where it shows output -- 
"Package fonts-powerline is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Error: Package 'fonts-powerline' has no installation candidate" 

but after restarting the terminal the setup procedure begins  and got the setup done .... is there any problem of not going with the step 
"sudo apt install fonts-powerline"??   // screenshot added after not going through "sudo apt install fonts-powerline" installation  process //
![Screenshot_2024-11-06_00-37-59](https://github.com/user-attachments/assets/3ebf33d8-7768-45e8-af10-a840f4029c0c)

**Comment by techchipnet** [comment]
You can install Powerline fonts from the following link: https://github.com/powerline/fonts.git
